ヘッダーの実装
traP-jp/traO-Judge-frontend pull request #37
Opened 2024-09-27 10:15 UTC by ZOI-dayo

resolve #15
ヘッダーを実装しました。`<TopNavBar>`として利用できます。
- デフォルトページのスタイルを消しています
  - リセットCSSを入れるべきかもです
- App.vueにmainを入れ、ヘッダー分のpaddingをつけています
- 必要になったので、PrimaryButton・SideMenuButtonも実装しました
- Figma上で定義されている色の一部をtailwind.config.jsに書きました
- Figma上で定義されているテキストスタイルの一部をmain.cssに書きました
- tailwindにデフォルトで入っていない長さをtailwind.config.jsに書きました
- ログイン後のドロップダウンについて、外側のどこがクリックされても閉じるように`click-outside-vue3`というライブラリを追加しました
  - メンテナンスされているか怪しいのでうまく代替する方法があればそうします

2024-09-27 12:55 UTC, ZOI-dayo commented
そういえば、ヘッダ内でもMaterial Symbolsを使っている部分があって空にしているので、 #38 を取り込んでから修正したほうが良さそう

2024-09-28 14:27 UTC, mathsuky reviewed
実装ありがとうございます！全体的にとても素晴らしいと思います:dekadekaarigatou:
いくつかコメントさせていただきましたので，確認よろしくお願いします。

それから，現在別PRでtailwindcssについてのlintを導入する作業を行なっているので，それがマージされ次第変更を取り込んでlintをかけてくださると助かります。よろしくお願いします。

2024-09-28 14:27 UTC, mathsuky commented on src/components/Navigations/TopNavbar.vue
> +const handler = (e: MouseEvent) => {
`handler`という名前が少し一般的すぎるような感じがします。
代替案を出すなら`menuStateHandler`とか`modalHandler`とか？

2024-09-28 14:27 UTC, mathsuky commented on src/components/Navigations/TopNavbar.vue
> +  }
```
  if (!(e.target instanceof HTMLElement) || e.target.closest('#top-navbar-menu')) {
    return
  }
```
のようにearly returnしても良いかも？

2024-09-28 14:27 UTC, mathsuky commented on src/components/Navigations/TopNavbar.vue
> +}
大体同じようなことをしているので，`setMenuState`のような関数一つにまとめてしまっても良いかも。

2024-09-28 15:52 UTC, ZOI-dayo commented on src/components/Navigations/TopNavbar.vue
> +}
addEventListenerとremoveEventListenerで分けないといけないので、
```javascript
const setMenuState = (state: boolean) => {
  isMenuOpen.value = state
  if(state) document.addEventListener('mousedown', menuCloseHandler)
  else document.removeEventListener('mousedown', menuCloseHandler)
}
```
となってあまり纏まりそうにないのですが、こんな感じで良いでしょうか...?

2024-09-28 16:33 UTC, ZOI-dayo commented on src/components/Navigations/TopNavbar.vue
> +}
toggleMenu()などで利用する際に簡潔に書けるようになるので、統合しました

2024-09-28 16:43 UTC, ZOI-dayo commented
レビューありがとうございます。コメントを参考に修正しました。

2024-09-28 16:56 UTC, YuHima03 requested changes
ごめん、今気づいたんだけど、`SideMenuButton` はサイドメニューじゃない場所にも使ってるから `MenuButton` の方がいいかも。

これはFigmaで `SideMenuButton` って命名してた僕が悪いです。
`MenuButton` に直しときます......。

2024-09-28 17:45 UTC, ZOI-dayo commented
そういえば、MenuButton内でアイコンを使う(今は空っぽにしている)ので、lintのPRだけでなく、Material SymbolsのPRもマージされてから、それを取り入れて修正を加えた上でこのPRをマージするほうが良いかもしれないです

2024-09-29 10:12 UTC, YuHima03 submitted a review, later dismissed

2024-09-29 11:11 UTC, YuHima03 reviewed
追加で1つ提案があります！！

`position: fixed` を `sticky` にすれば、 `<main>` 要素にパディングを設定しなくて済むので、そっちの方が良いかもしれない。

何度もコメント投げちゃって本当に申し訳ないんだけど、確認お願いします。

2024-09-30 05:14 UTC, mathsuky commented
2個伝え忘れていたことがありました
- formatをかけておいてもらえると助かります:pray:
- `npm audit`してみてもし脆弱性がありそうだったら`npm audit fix`などで適当に対処しておいてもらえるとありがたいです

2024-09-30 06:32 UTC, mathsuky commented
自分が最初に指摘したところの修正はとても良さそうです！
一番重要なことを忘れていた，ごめんなさい！

2024-09-30 08:25 UTC, ZOI-dayo commented
フォーマット・auditの解消・Material Symbols対応をしました

2024-09-30 09:34 UTC, YuHima03 requested changes
修正ありがとう！

やっておいてほしいことが1点だけあって、Figmaにある通り `MenuButton` の角丸とホバー時の背景色を指定しておいてほしいです。

何度も何度も申し訳ないけど、お願いします。

2024-09-30 09:34 UTC, YuHima03 commented on tailwind.config.js
`brand-light-primary` の色定義を追加しておいてほしいです。

2024-09-30 09:34 UTC, YuHima03 commented on src/components/Navigations/MenuButton.vue
もし可能だったら、Figmaにある通りボタンの `Selected` 時のスタイルも記述しておいてほしいかも。

ただ、これはサイドパネルのコンポーネントを作るときでも大丈夫です。

2024-09-30 09:34 UTC, YuHima03 commented on src/components/Navigations/MenuButton.vue
> +    class="flex w-full items-center gap-2 px-4 py-1"
ボタンの角丸と、ホバー時の背景を設定しておいてほしいです。

```suggestion
    class="flex w-full items-center gap-2 rounded-lg px-4 py-1 hover:bg-brand-light-primary"
```

2024-09-30 12:42 UTC, YuHima03 commented
`Selected` の実装までしてくれてありがとう！！

これ以外に気になったことはなかったので、あとは他のレビュワーの方にお任せします。

2024-09-30 18:18 UTC, ZOI-dayo commented
このPRのコードはeslintのフォーマットに従っているので、 #43 がマージされたらそれを取り込んでPrietterでフォーマットしてからcloseしたほうがいいかも

2024-10-04 04:00 UTC, mathsuky requested changes
1点だけ修正をお願いします:pray:

2024-10-04 10:49 UTC, mathsuky approved these changes
LGTM ありがとうございます！

2024-10-04 10:50 UTC, YuHima03 approved these changes

2024-10-04 10:51 UTC, merged