ログインページ見た目実装
traP-jp/traO-Judge-frontend pull request #74
Opened 2024-12-15 05:48 UTC by kitsne241

再掲

- Google のロゴに関しては[ガイドライン](https://developers.google.com/identity/branding-guidelines?hl=ja)がRobotoを用いて丸い形のボタンを作ること以外認めない？ようにも読めるので、実際どうなのかを伺いたいです
- traQ の白抜きでないバージョンのロゴを公式に配布している場所が見つからなかったので、とりあえずデザイン部分のSVGをそのまま拝借しました
- 若干文字が太い気がします。Noto Sans JP かつ 500 で合わせてあるはずなので不思議です

<img width="883" alt="スクリーンショット 2024-12-15 14 44 23" src="https://github.com/user-attachments/assets/4ce33d59-9e85-469c-9da2-4a7f3dc64a08" />

2024-12-15 06:00 UTC, mathsuky commented
取り急ぎ1つ目だけ
出先でさっと見ただけなのでまた後で確認する必要があるかもしれないですが、Download Pre-Approved Brand Iconsというセクションから丸いボタンと四角いボタンの画像がダウンロードできるので、それを用いておけばよさそうに思います。(その下の禁止事項を守るのは前提として)

2024-12-15 06:01 UTC, mathsuky commented
@YuHima03 
OAuth周りのデザインを作るうえでドキュメントのどのあたりを見ました？&どこからダウンロードしました？
また2つ目の質問に関連して、traQのアイコンはどこから持ってきましたか？

2024-12-15 06:52 UTC, kitsne241 commented
> 取り急ぎ1つ目だけ 出先でさっと見ただけなのでまた後で確認する必要があるかもしれないですが、Download Pre-Approved Brand Iconsというセクションから丸いボタンと四角いボタンの画像がダウンロードできるので、それを用いておけばよさそうに思います。(その下の禁止事項を守るのは前提として)

ダウンロードできる画像はいずれも「Continue with Google」などと書かれているボタンのもので、日本語で「Google でログイン」と書かれてはおらず、アスペクト比もデザインファイルにて指定されたデザインとは大きく異なります。ガイドラインに載っている形式を優先するならば以下どちらかになりそうです
- Googleのログインボタンのみガイドライン指定に忠実に従い、他のボタンはデザインファイルに合わせる
- 他のボタンも「Continue with traQ」のようにスタイルを合わせる

2024-12-15 06:53 UTC, kitsne241 commented
他社サービスではどう取り扱っているのかを調べました（具体的には [Trello](https://trello.com/)、[OpenAI](https://platform.openai.com/login?launch) など）が、必ずしもGoogleが示すガイドラインに厳密に従っているわけではなさそうです。ガイドラインの Don't の例には当てはまっていませんが、Do の例に忠実に従っているわけでもない感じです。Do の例はあくまでベストプラクティスであると捉えて良いのでしょうか？

2024-12-15 06:57 UTC, mathsuky commented
自分は文字の書いていないグーグルのアイコンだけのものを指しているつもりでした、日本語が悪くて申し訳ないです🙏
それがPre-Approved Brand Iconsとして配布されているということは、それを用いてガイドラインに従う範囲でボタンを作成することは問題ないのではないかと考えました。(ガイドラインと現行のFigmaデザインがコンフリクトしているかどうかは確認していません)

> ダウンロードできる画像はいずれも「Continue with Google」などと書かれているボタンのもので、日本語で「Google でログイン」と書かれてはおらず、アスペクト比もデザインファイルにて指定されたデザインとは大きく異なります。ガイドラインに載っている形式を優先するならば以下どちらかになりそうです
> 
> * Googleのログインボタンのみガイドライン指定に忠実に従い、他のボタンはデザインファイルに合わせる
> * 他のボタンも「Continue with traQ」のようにスタイルを合わせる

2024-12-15 07:00 UTC, mathsuky commented
> 他社サービスではどう取り扱っているのかを調べました（具体的には [Trello](https://trello.com/)、[OpenAI](https://platform.openai.com/login?launch) など）が、必ずしもGoogleが示すガイドラインに厳密に従っているわけではなさそうです。ガイドラインの Don't の例には当てはまっていませんが、Do の例に忠実に従っているわけでもない感じです。Do の例はあくまでベストプラクティスであると捉えて良いのでしょうか？

後できちんと確認しますが、Dontに反していなければ良いように思います。このあたりはtidusくんの話を聞きたい感じもあります。

2024-12-15 07:15 UTC, YuHima03 commented
@mathsuky @kitsne241 

返信遅くなってすみません！🙇‍♂️

1. Googleについては [Sign in with Google Branding Guidelines](https://developers.google.com/identity/branding-guidelines#custom-button) や [Brand Resource Center](https://about.google/brand-resource-center/) を見て、ロゴはFigmaで使いまわす都合上 <https://about.google/brand-resource-center/logos-list/#g> から落としています. \
  ボタンのデザインですが, 自分も他社サービスを見たりして今の状態にしていた気がします. \
  Googleのロゴを置いてるページは実は他にもあるので, 詳しい話は別枠でやりたいです.
2. traQのアイコンは, traQのFigmaデザインファイルから取ってきています.  \
  (ここにリンク張ってもいいのかちょっと分からないのでtraQのほうでお伝えします)
3. 文字が太く見える件ですが, 僕の方のWindows環境では確認できなかったです.
  (そもそも Noto Sans JP フォントが入っていない可能性があるか, ブラウザのレンダラーの違いかもしれないです.)

2024-12-16 01:16 UTC, ZOI-dayo requested changes
@kitsne241 
ありがとうございます! めちゃくちゃ良さそうです!
いくつか細かい点に関してコメントを書いたので見てほしいです。
(デザインがまだ完全には確定していないので、現時点では変更しなくて良い場所もあるかもしれないです。その場合は無視していただけるとありがたいです。)

2024-12-16 01:16 UTC, ZOI-dayo commented on src/views/LoginView.vue
> +      <h1 class="mb-5 h-9 font-primary text-28px font-medium text-[#1E1E1E]">ログイン</h1>
詳しくは36行目への指摘を見てほしいのですが、family・size・weightに関しては`.fontstyle-ui-title`を使用していただけると簡潔だと思います。
```suggestion
      <h1 class="mb-5 fontstyle-ui-title text-[#1E1E1E]">ログイン</h1>
```
(なお、このような文字のスタイル名(`fontstyle-hoge-fuga`)は、Figma上でテキストをクリックすると楽に確認できます!)

2024-12-16 01:16 UTC, ZOI-dayo commented on tailwind.config.js
>        }
他のコメントの変更で`px`単位は不要になっていると思うので、ここは消してもらって大丈夫なはずです!

2024-12-16 01:19 UTC, YuHima03 commented on src/views/LoginView.vue
> +          <input placeholder="パスワード" class="input" />
@ZOI-dayo  @kitsne241 

コンポーネントの方使ってください 🙏 

コンポーネント使うとあとから弄れて非常に楽になりますし、今置いてる画面デザインは暫定のものなので……

2024-12-16 02:05 UTC, kitsne241 commented
色々とありがとうございます！不慣れなものでお手数おかけしてすみません…
1. ボタンの内部にブロック要素を置くと表示が崩れる可能性があるのでインライン要素、一行のテキストの場合一般に `<span>` を用いる
2. メールアドレスやパスワードのフォームはコンポーネントが用意されているのでそれを用いる
3. 予め family・size・weight のパターンをまとめたクラスが用意されていて、Figmaでその名前が確認できるのでそれを用いる
4. tailwind.config.js における font primary の変更と fontSize の変更をもとに戻す

とりあえずこの4点ですね。今週中には修正します :pray:

2024-12-20 00:22 UTC, kitsne241 commented
とりあえずご指摘いただいた部分に変更を加えました
色指定はとりあえず `'text-[#1E1E1E]'` のような Arbitrary value による指定を残しました。もし `tailwind.config.js` の theme > colors に既にある色に統一すべきであればまた教えてください

2024-12-21 03:26 UTC, ZOI-dayo submitted a review, later dismissed
良さそうです! ありがとうございます!!
まだデザインが確定していないので、カラーコードを直接指定している部分に関してはひとまずこのままでいいです。 (後でデザインが確定した時に直す予定です)

マージしてしまって大丈夫だと思います! :kansya:

2024-12-21 03:27 UTC, ZOI-dayo commented
ア! コンフリクトがあるのでその修正だけお願いします!

2024-12-21 09:50 UTC, ZOI-dayo approved these changes
良さそうです! :deakdekaarigatou:

2024-12-21 09:55 UTC, ZOI-dayo commented
ちなみに: 追加コミットをした際はApproveが外れてしまうので、Issue画面右上のReviewersからRe-request reviewを送ってもらえると通知が行ってレビューが早くなります

2024-12-21 15:23 UTC, merged